现场管理界面，新增正在泄压信息提示
marklion/mobile_trade pull request #27
Opened 2024-07-20 07:59 UTC by debugerlu

现场管理界面，弹出框新增正在泄压文本提示

2024-07-21 04:27 UTC, marklion requested changes
搞错了哈，需求是这样，在输入框里靠右的位置添加一个按钮，按一下之后才把正在泄压这四个字赋值给seal_no变量

2024-07-22 03:03 UTC, debugerlu commented
> 搞错了哈，需求是这样，在输入框里靠右的位置添加一个按钮，按一下之后才把正在泄压这四个字赋值给seal_no变量

已改正
![image](https://github.com/user-attachments/assets/216753b8-59b3-48a9-846b-b47342fe8ac4)

2024-07-30 08:36 UTC, marklion reviewed
格式化

2024-07-30 20:07 UTC, marklion commented on mt_gui/pages/Field.vue
> +            if (e.text === "确定") {
这个修改应该去掉，这块我们的设计就是：点击取消键代表取消车辆确认

2024-07-31 03:40 UTC, marklion approved these changes

2024-07-31 06:25 UTC, merged