客户端登陆信息校验
marklion/mobile_trade pull request #29
Opened 2024-07-20 08:09 UTC by debugerlu

小程序登陆账号密码为必填项

2024-07-21 04:14 UTC, marklion commented on mt_gui/pages/Login.vue
> +				rule: ["required"],
如果这里的rule只有一个，那么msg应该也只有一个,也就是数量相等。例如：
```
name: "password",
rule: ["required", 'isNumber'],
msg: ["请输入密码", 'value must be positive number']
```

2024-07-21 04:18 UTC, marklion requested changes
两点需要改一下：
1. 参考我的第一个comment
2. 代码需要格式化一下，建议用专门的vue代码格式化插件整一下，代码库中的风格是：4个空格缩进。

2024-07-22 03:57 UTC, debugerlu commented
> 两点需要改一下：
> 
> 1. 参考我的第一个comment
> 2. 代码需要格式化一下，建议用专门的vue代码格式化插件整一下，代码库中的风格是：4个空格缩进。

2024-07-22 04:03 UTC, debugerlu commented
> 两点需要改一下：
> 
> 1. 参考我的第一个comment
> 2. 代码需要格式化一下，建议用专门的vue代码格式化插件整一下，代码库中的风格是：4个空格缩进。

已解决

2024-07-30 08:35 UTC, marklion reviewed
格式化一下

2024-07-30 08:35 UTC, marklion commented on mt_gui/pages/Login.vue
> +                rule: ["required","isNumber"],
应该用isMobile

2024-07-30 20:13 UTC, marklion approved these changes

2024-07-31 02:39 UTC, merged