统计图改为柱状
marklion/mobile_trade pull request #40
Opened 2024-08-08 08:40 UTC by debugerlu

![image](https://github.com/user-attachments/assets/a5b5303c-54d6-4b1a-b619-a5c6adc82197)

2024-08-08 10:01 UTC, marklion commented
需要修改成这个样子哈：
![image](https://github.com/user-attachments/assets/02c366c5-2b6b-4d24-8dec-5a5ba5bf8207)

2024-08-08 10:23 UTC, marklion requested changes
需要修改成这个样子哈：
![image](https://github.com/user-attachments/assets/02c366c5-2b6b-4d24-8dec-5a5ba5bf8207)

2024-08-09 08:13 UTC, debugerlu commented
![home_column](https://github.com/user-attachments/assets/c3ee80ba-aa63-48fb-848a-00b54e5ecad7)
![home_column_single](https://github.com/user-attachments/assets/1939f9f2-ebba-423f-8404-7fd4b3c3d99e)

2024-08-09 08:40 UTC, debugerlu commented
全局颜色统一
![home_column_single](https://github.com/user-attachments/assets/57fee4ec-e33a-409e-9744-8411bf8692c6)

2024-08-09 10:43 UTC, marklion approved these changes

2024-08-09 11:12 UTC, marklion approved these changes

2024-08-09 11:19 UTC, merged