fix
marklion/mobile_trade pull request #42
Opened 2024-08-08 09:47 UTC by debugerlu

2024-08-08 10:12 UTC, marklion requested changes

2024-08-08 10:12 UTC, marklion commented on mt_gui/pages/OrderList.vue
> -    <!-- <fui-gallery zIndex="1004" :urls="one_att" :show="show_one_att" @hide="show_one_att = false"></fui-gallery> -->
删掉这些东西是为啥呀?我记得这是之前一个需求该进去的吧

2024-08-09 09:03 UTC, debugerlu commented on mt_gui/pages/OrderList.vue
> -    <!-- <fui-gallery zIndex="1004" :urls="one_att" :show="show_one_att" @hide="show_one_att = false"></fui-gallery> -->
是的，自动合并后我没及时pull到本地导致的

2024-08-09 09:53 UTC, marklion approved these changes

2024-08-09 10:54 UTC, marklion requested changes
两点：
1.在这个文件也要改一下类似的东西：
2.rebase之后再提交
![image](https://github.com/user-attachments/assets/87a6323f-82f6-4873-a600-ca812566ce86)

2024-08-09 12:08 UTC, marklion approved these changes

2024-08-09 12:08 UTC, merged