ZYZL-393--excel导入、手动创建车队信息时删除多余空格
marklion/mobile_trade pull request #48
Opened 2024-08-15 03:12 UTC by debugerlu

![image](https://github.com/user-attachments/assets/acee84de-25c2-40b6-9304-00a66ce359cb)
![image](https://github.com/user-attachments/assets/6ecc6fe8-9e03-4b4e-ad64-114eceeba61f)

2024-08-19 03:58 UTC, marklion requested changes
1. 还需要对车辆信息表写脚本清除脏数据
2. 脚本执行的时机改为可控，比如增加一个API干这个事

2024-08-21 10:42 UTC, marklion requested changes

2024-08-21 10:42 UTC, marklion commented on api/lib/clean_driver.js
> +                    await vehicle.destroy({ transaction })
删除之前要改变计划表、车队表、安检表的关联

2024-08-21 10:42 UTC, marklion commented on api/lib/clean_driver.js
> +                        // 关联计划、合同、车队、考试
合同表和司机表没有关联，不用处理

2024-08-26 17:11 UTC, marklion requested changes

2024-08-26 17:11 UTC, marklion commented on api/lib/clean_driver.js
> +                        await sq.query(
这块直接写成以下的写法应该可以吧：
driver.phone = CleandPhone;
driver.xxx = cleandXxx;
...
await driver.save({transaction})

2024-08-26 17:11 UTC, marklion commented on api/lib/clean_driver.js
> +                            [db_opt.Op.or]:{
这里应该只判断phone是否相等，不应该用or

2024-08-26 17:11 UTC, marklion commented on api/lib/clean_driver.js
> +                                'UPDATE OR IGNORE vehicle SET plate = :plate WHERE id = :id',
类似上边的更新问题，应该用save可以搞定

2024-08-27 01:21 UTC, debugerlu commented on api/lib/clean_driver.js
> +                                'UPDATE OR IGNORE vehicle SET plate = :plate WHERE id = :id',
也是唯一字段不能用save方式

2024-08-27 08:29 UTC, marklion approved these changes

2024-08-27 08:29 UTC, merged