ZYZL-424--基于公司添加是否支持泄压配置选项
marklion/mobile_trade pull request #64
Opened 2024-09-02 06:39 UTC by debugerlu

![config](https://github.com/user-attachments/assets/ffce65ce-20b8-44e2-8e81-729663b9efed)
![config1](https://github.com/user-attachments/assets/d2f510c4-381c-4de8-85d2-9a054420390f)
![config2](https://github.com/user-attachments/assets/0fbe70b5-740c-4968-ad36-3fa99f2c30b5)

2024-09-04 11:35 UTC, marklion requested changes

2024-09-04 11:35 UTC, marklion commented on api/module/global_module.js
> +                pressure_config: { type: Boolean, have_to: true, mean: '是否支持泄压配置', example: 'true' },
这个example字段应该设为布尔值true吧，如果设定为字符串的话我记得会有问题来着

2024-09-04 11:36 UTC, marklion requested changes

2024-09-04 11:36 UTC, marklion commented on mt_gui/pages/Field.vue
> +            <slot v-if="focus_company.pressure_config" name="default">
这里应该判定stuff.company是否支持泄压，也就是接单方公司是否配置了泄压

2024-09-05 07:39 UTC, debugerlu commented on mt_gui/pages/Field.vue
> +            <slot v-if="focus_company.pressure_config" name="default">
问题已修复

2024-09-05 07:46 UTC, marklion approved these changes

2024-09-05 08:04 UTC, marklion approved these changes

2024-09-05 08:05 UTC, merged