ZYZL-436--增加黑名单功能
marklion/mobile_trade pull request #75
Opened 2024-09-19 06:29 UTC by debugerlu

2024-09-23 01:36 UTC, marklion commented
这个没做完吧，我在JIRA里有写昂，要有自动化用例新增了

2024-09-25 00:20 UTC, marklion requested changes

2024-09-25 00:20 UTC, marklion commented on api/module/stuff_module.js
> +                type: { type: String, have_to: true, mean: '黑名单类型', example: 'vehicle' },
按照当前的编程风格，删除记录时应该将记录本身的id（或多个id）作为参数

2024-09-25 00:20 UTC, marklion commented on api/module/stuff_module.js
> +                    type: Array, mean: '黑名单列表', explain: {
这里建议将driver 或vehicle 展开，而不是只返回id，可以参考其他嵌套结构的实现方法

2024-09-25 00:20 UTC, marklion commented on mt_gui/pages/OrderList.vue
> +                <u-cell title="挂车"">
多余的"  
<u-cell title="挂车"">

2024-09-25 00:20 UTC, marklion commented on mt_gui/pages/OrderList.vue
> +                            <fui-button btnSize="mini" text="加入黑名单" @click="add_to_blacklist(focus_plan.main_vehicle.id, 'vehicle')"></fui-button>
这样的按钮要包裹到权限控制组件中

2024-09-25 00:20 UTC, marklion commented on mt_gui/App.vue
> +uni-modal {
这个全局样式会不会影响某些页面呀，例如合同管理页面添加合同时选择起始日期的操作，建议测一下

2024-09-25 09:27 UTC, debugerlu commented on mt_gui/pages/OrderList.vue
> +                            <fui-button btnSize="mini" text="加入黑名单" @click="add_to_blacklist(focus_plan.main_vehicle.id, 'vehicle')"></fui-button>
这里需不需要加一个blacklist的模块权限，目前是物料模块包含了黑名单

2024-09-25 10:21 UTC, marklion requested changes

2024-09-25 10:21 UTC, marklion commented on api/module/stuff_module.js
> +                    return { blacklist: ret };
这里应该用count函数查询到总数是多少，然后赋值给total字段并返回。可以参考其他获取接口实现

2024-09-25 10:21 UTC, marklion commented on mt_gui/subPage1/BlackList.vue
> +                this.vehicleList = response.vehicle_teams.flatMap(team =>
这块实现不应该牵扯/global/get_vehicle_team这个接口，建议参考其他的获取类的数据前端实现。
几个要素：
1. 应该用list-show这个组件，把获取数据的函数传递到组件中
2. 获取数据的函数注意传递页码给后端

2024-09-26 09:54 UTC, debugerlu commented on mt_gui/App.vue
> +uni-modal {
改用用fui弹出框实现

2024-09-26 10:57 UTC, marklion requested changes

2024-09-26 10:57 UTC, marklion commented on api/module/common.js
> +            let company = await rbac_lib.get_company_by_token(token);
这块修改不要了，直接在图中这个地方整一下就能搞定更新的场景：
![image](https://github.com/user-attachments/assets/d5b8f9d4-215a-46b6-84b6-a131da993d91)

2024-09-26 10:57 UTC, marklion commented on mt_gui/subPage1/BlackList.vue
> +    <fui-bottom-popup :show="show_popup" @close="show_popup=false">
这块做新增的时候应该让用户输入车牌号或司机手机号，而不是从车队中获取，对于一般的工厂来说，是不维护车队的

2024-09-26 10:57 UTC, marklion commented on mt_gui/subPage1/BlackList.vue
> +                    <fui-label v-if="item.driver" v-for="item in blacklistData" :key="item.id">
if 不要和for整在一起，上边那段也是一样

2024-09-26 10:57 UTC, marklion commented on mt_gui/subPage1/Stuff.vue
> +        this.$refs?.blacklist_ref?.getBlacklist();
这块应该把组件内的this.$refs.blacklist.refresh();封装起来后调用

2024-09-27 10:02 UTC, marklion requested changes

2024-09-27 10:41 UTC, marklion approved these changes

2024-09-27 10:55 UTC, merged